name: 👀Code Review

permissions: write-all

on:
  pull_request:
  pull_request_review_comment:
    types: [created]
    
    
    # some cmment

concurrency:
  group: >-
    ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}
    -${{ github.workflow }}-${{ github.event_name == 'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.getContent({
              owner: 'adeo',
              repo: 'ccdp--java-sample-api',
              path: '.github/workflows/check-pr.yml',
              ref: 'refs/heads/openai-pr-review'
            })
      - uses: fluxninja/openai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # pragma: allowlist secret
        with:
          debug: true
          review_simple_changes: true
          review_comment_lgtm: true
